development:
  adapter: postgresql
  encoding: unicode
  database: todo-on-rails-development
  pool: 10
  connections: 10
  username: <%= ENV['USER'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: todo-on-rails-test
  pool: 10
  connections: 10
  username: <%= ENV['USER'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: todo-on-rails
  pool: 10
  connections: 10
  username: <%= ENV['USER'] %>
